#!/usr/bin/env php
<?php

set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php';

use Symcloud\Application\Jibe\DependencyInjection\CommandsCompilerPass;
use Symcloud\Application\Jibe\DependencyInjection\JibeExtension;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;

$configDirectory = '.symcloud';
if (!is_dir($configDirectory)) {
    mkdir($configDirectory);
}

define('PARAMETER_FILE', realpath($configDirectory).'/parameters.yml');
define('ROOT_FOLDER', dirname(realpath($configDirectory)));

$input = new \Symfony\Component\Console\Input\ArgvInput();
$output = new \Symfony\Component\Console\Output\ConsoleOutput();

define('DEBUG', true === $input->hasParameterOption(array('--debug', '-d')));

$container = new ContainerBuilder();

$container->set('jibe.application.output', $output);
$container->set('jibe.application.input', $input);

$locator = new FileLocator($configDirectory);

try {
    $ymlLoader = new Loader\YamlFileLoader($container, $locator);
    $ymlLoader->load('parameters.yml');
} catch (\Exception $ex) {
}

$extension = new JibeExtension();
$extension->load(array(), $container);

$container->addCompilerPass(new CommandsCompilerPass());

$container->compile();

$app = $container->get('jibe.application');
$app->run($input, $output);
